# coding: utf-8
#
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py
import os
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import remove_self_loops, add_self_loops, degree
import torch_geometric

from common.abstract_recommender import GeneralRecommender
from common.loss import BPRLoss, EmbLoss
from common.init import xavier_uniform_initialization
from torch_geometric.utils import get_laplacian
from torch_geometric.utils import normalized_cut
import scipy.sparse as sp
from scipy.sparse.linalg import eigsh

class SSR(GeneralRecommender):
    def __init__(self, config, dataset):
        super(SSR, self).__init__(config, dataset)
        num_user = self.n_users
        num_item = self.n_items
        batch_size = config['train_batch_size']
        dim_x = config['embedding_size']
        self.feat_embed_dim = config['feat_embed_dim']
        self.n_layers = config['n_mm_layers']
        self.knn_k = config['knn_k']
        self.mm_image_weight = config['mm_image_weight']
        has_id = True
        self.out_mode = config['out_mode']   # "aggr" "spec" "mix"
        self.mix_alpha = config['mix_alpha']
        self.mask_flag = "band_drop"       # "band_drop" or "noise_inter"
        self.mask_rate = config['ma_rate']
        self.band_num = config['band_num']
        self.k_poly = config['k_poly']
        self.tau = config['tau']
        self.hid_sim = 16
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.k = 40
        self.aggr_mode = config['aggr_mode']
        self.user_aggr_mode = 'softmax'
        self.num_layer = config['num_layers']
        self.cold_start = 0
        self.dataset = dataset
        # self.construction = 'weighted_max'
        self.construction = 'cat'
        self.reg_weight = config['reg_weight']
        self.cl_weight = config['cl_weight']
        self.ma_weight = config['ma_weight']
        self.drop_rate = 0.1
        self.v_rep = None
        self.t_rep = None
        self.v_preference = None
        self.t_preference = None
        self.dim_latent = 64
        self.dim_feat = 128
        self.MLP_v = nn.Linear(self.dim_latent, self.dim_latent, bias=False)
        self.MLP_t = nn.Linear(self.dim_latent, self.dim_latent, bias=False)
        self.mm_adj = None

        self.user_id_embedding = nn.Embedding(self.n_users, self.dim_latent)
        self.item_id_embedding = nn.Embedding(self.n_items, self.dim_latent)
        nn.init.xavier_uniform_(self.user_id_embedding.weight)
        nn.init.xavier_uniform_(self.item_id_embedding.weight)

        dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        #self.user_graph_dict = np.load(os.path.join(dataset_path, config['user_graph_dict_file']),
        #                               allow_pickle=True).item()
        
        self.has_user_graph = False  # default flag
        user_emb_path = os.path.join(dataset_path, config['user_emb_file'])

        if os.path.isfile(user_emb_path):
            user_emb = np.load(user_emb_path, allow_pickle=True)
            self.user_emb = torch.from_numpy(user_emb).to(self.device)
            print(">>>>Load user emb from: ", user_emb_path)
            indices, user_adj = self.get_knn_adj_mat(self.user_emb)
            self.user_adj = user_adj
            self.has_user_graph = True
        else:
            self.has_user_graph = False
            print(f">>>>Not found user_emb_file from {user_emb_path}")

        mm_adj_file = os.path.join(dataset_path, 'mm_adj_{}.pt'.format(self.knn_k))
        self.has_item_graph = True
        if self.v_feat is not None:
            self.image_embedding = nn.Embedding.from_pretrained(self.v_feat, freeze=False)
            self.image_trs = nn.Linear(self.v_feat.shape[1], self.feat_embed_dim)
        if self.t_feat is not None:
            self.text_embedding = nn.Embedding.from_pretrained(self.t_feat, freeze=False)
            self.text_trs = nn.Linear(self.t_feat.shape[1], self.feat_embed_dim)

        if os.path.exists(mm_adj_file) and False:
            self.mm_adj = torch.load(mm_adj_file)
            print(">>>>>Loaded from: ", mm_adj_file)
        else:
            if self.v_feat is not None:
                indices, image_adj = self.get_knn_adj_mat(self.image_embedding.weight.detach())
                self.mm_adj = image_adj
            if self.t_feat is not None:
                indices, text_adj = self.get_knn_adj_mat(self.text_embedding.weight.detach())
                self.mm_adj = text_adj
            if self.v_feat is not None and self.t_feat is not None:
                self.mm_adj = self.mm_image_weight * image_adj + (1.0 - self.mm_image_weight) * text_adj
                del text_adj
                del image_adj
            torch.save(self.mm_adj, mm_adj_file)
            print(">>>>>Save mm_adj to: ", mm_adj_file)

        # packing interaction in training into edge_index
        train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)
        edge_index = self.pack_edge_index(train_interactions)
        self.edge_index = torch.tensor(edge_index, dtype=torch.long).t().contiguous().to(self.device)
        self.edge_index = torch.cat((self.edge_index, self.edge_index[[1, 0]]), dim=1)

        # pdb.set_trace()
        self.weight_u = nn.Parameter(nn.init.xavier_normal_(
            torch.tensor(np.random.randn(self.num_user, 3, 1), dtype=torch.float32, requires_grad=True)))
        self.weight_u.data = F.softmax(self.weight_u, dim=1)

        self.weight_i = nn.Parameter(nn.init.xavier_normal_(
            torch.tensor(np.random.randn(self.num_item, 2, 1), dtype=torch.float32, requires_grad=True)))
        self.weight_i.data = F.softmax(self.weight_i, dim=1)

        self.item_index = torch.zeros([self.num_item], dtype=torch.long)
        index = []
        for i in range(self.num_item):
            self.item_index[i] = i
            index.append(i)
        self.drop_percent = self.drop_rate
        self.single_percent = 1
        self.double_percent = 0

        drop_item = torch.tensor(
            np.random.choice(self.item_index, int(self.num_item * self.drop_percent), replace=False))
        drop_item_single = drop_item[:int(self.single_percent * len(drop_item))]

        self.dropv_node_idx_single = drop_item_single[:int(len(drop_item_single) * 1 / 3)]
        self.dropt_node_idx_single = drop_item_single[int(len(drop_item_single) * 2 / 3):]

        self.dropv_node_idx = self.dropv_node_idx_single
        self.dropt_node_idx = self.dropt_node_idx_single

        mask_cnt = torch.zeros(self.num_item, dtype=int).tolist()
        for edge in edge_index:
            mask_cnt[edge[1] - self.num_user] += 1
        mask_dropv = []
        mask_dropt = []
        for idx, num in enumerate(mask_cnt):
            temp_false = [False] * num
            temp_true = [True] * num
            mask_dropv.extend(temp_false) if idx in self.dropv_node_idx else mask_dropv.extend(temp_true)
            mask_dropt.extend(temp_false) if idx in self.dropt_node_idx else mask_dropt.extend(temp_true)

        edge_index = edge_index[np.lexsort(edge_index.T[1, None])]
        edge_index_dropv = edge_index[mask_dropv]
        edge_index_dropt = edge_index[mask_dropt]

        self.edge_index_dropv = torch.tensor(edge_index_dropv).t().contiguous().to(self.device)
        self.edge_index_dropt = torch.tensor(edge_index_dropt).t().contiguous().to(self.device)

        self.edge_index_dropv = torch.cat((self.edge_index_dropv, self.edge_index_dropv[[1, 0]]), dim=1)
        self.edge_index_dropt = torch.cat((self.edge_index_dropt, self.edge_index_dropt[[1, 0]]), dim=1)

        self.MLP_user = nn.Linear(self.dim_latent * 2, self.dim_latent)

        if self.v_feat is not None:
            self.v_drop_ze = torch.zeros(len(self.dropv_node_idx), self.v_feat.size(1)).to(self.device)
            self.v_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                             num_layer=self.num_layer, has_id=has_id, dropout=self.drop_rate, dim_latent=self.dim_latent,
                             device=self.device, features=self.v_feat)  # 256)
        if self.t_feat is not None:
            self.t_drop_ze = torch.zeros(len(self.dropt_node_idx), self.t_feat.size(1)).to(self.device)
            self.t_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                             num_layer=self.num_layer, has_id=has_id, dropout=self.drop_rate, dim_latent=self.dim_latent,
                             device=self.device, features=self.t_feat)
        
        self.id_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                             num_layer=self.num_layer, has_id=has_id, dropout=self.drop_rate, dim_latent=None,
                             device=self.device, features=self.item_id_embedding.weight)

        self.user_graph = User_Graph_sample(num_user, 'add', self.dim_latent)

        self.result_embed = nn.Parameter(
            nn.init.xavier_normal_(torch.tensor(np.random.randn(num_user + num_item, dim_x)))).to(self.device)

        # === define the spectral transformation processor
        # here we registered lap_user first, latter we will fill it
        self.Spec_Processor = SpectralGraphSignalProcessor(dim_x, dim_x, dim_x, self.band_num, self.k_poly, self.device, self.hid_sim)
        
        # === define the spectral cacluation module
        self.Spec_Operator = SpectralCalculateOperator(dim_x, dim_x, dim_x, self.band_num, self.device, self.mask_flag, self.mask_rate, self.hid_sim)
        
        # === attention, we should calculate in advance
        # calculate graph Laplacian as:
        edge_index_lap, edge_weight_lap = get_laplacian(self.edge_index, normalization='sym')
        lap_size = self.num_user + self.num_item
        lap_sym = torch.sparse_coo_tensor(
            edge_index_lap, edge_weight_lap, (lap_size, lap_size), device=self.device
        ).coalesce()

        # use eigsh: sym lap（0..2), same feature vector（-I don't affect vector）
        self.Spec_Processor.lap_user_raw = lap_sym

        # if we use to Cheb [-1,1]
        I = sparse_eye(lap_size, self.device)
        self.Spec_Processor.lap_user = (lap_sym - I).coalesce()
        self.Spec_Processor.lap_item = self.Spec_Processor.lap_user
        
        #
        self.cheb_bank = ChebFilterBank(M=self.band_num, K_poly=self.k_poly)
        self.fusion_gate = nn.Parameter(torch.tensor(0.0))

    def get_knn_adj_mat(self, mm_embeddings):
        context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
        adj_size = sim.size()
        del sim
        # construct sparse adj
        indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
        indices0 = torch.unsqueeze(indices0, 1)
        indices0 = indices0.expand(-1, self.knn_k)
        indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
        # norm
        return indices, self.compute_normalized_laplacian(indices, adj_size)

    def compute_normalized_laplacian(self, indices, adj_size):
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        rows_inv_sqrt = r_inv_sqrt[indices[0]]
        cols_inv_sqrt = r_inv_sqrt[indices[1]]
        values = rows_inv_sqrt * cols_inv_sqrt
        return torch.sparse.FloatTensor(indices, values, adj_size)

    def pre_epoch_processing(self):
        if self.has_user_graph:
            self.epoch_user_graph, self.user_weight_matrix = self.topk_sample(self.k)
            self.user_weight_matrix = self.user_weight_matrix.to(self.device)
        else:
            pass

    def pack_edge_index(self, inter_mat):
        rows = inter_mat.row
        cols = inter_mat.col + self.n_users
        return np.column_stack((rows, cols))

    def forward(self):
        representation = None
        self.id_rep, self.id_preference = self.id_gcn(self.edge_index_dropv, self.edge_index, self.item_id_embedding.weight)

        if self.v_feat is not None:
            self.v_rep, self.v_preference = self.v_gcn(self.edge_index_dropv, self.edge_index, self.image_embedding.weight)
            representation = self.v_rep
        if self.t_feat is not None:
            self.t_rep, self.t_preference = self.t_gcn(self.edge_index_dropt, self.edge_index, self.text_embedding.weight)
            if representation is None:
                representation = self.t_rep
            else:
                representation = torch.cat((self.id_rep, self.v_rep, self.t_rep), dim=1)

        if self.construction == 'weighted_sum':
            if self.v_rep is not None:
                self.v_rep = torch.unsqueeze(self.v_rep, 2)
                user_rep = self.v_rep[:self.num_user]
            if self.t_rep is not None:
                self.t_rep = torch.unsqueeze(self.t_rep, 2)
                user_rep = self.t_rep[:self.num_user]
            if self.v_rep is not None and self.t_rep is not None:
                user_rep = torch.matmul(torch.cat((self.v_rep[:self.num_user], self.t_rep[:self.num_user]), dim=2),
                                        self.weight_u)
            user_rep = torch.squeeze(user_rep)

        if self.construction == 'weighted_max':
            # pdb.set_trace()
            self.v_rep = torch.unsqueeze(self.v_rep, 2)

            self.t_rep = torch.unsqueeze(self.t_rep, 2)

            user_rep = torch.cat((self.v_rep[:self.num_user], self.t_rep[:self.num_user]), dim=2)
            user_rep = self.weight_u.transpose(1, 2) * user_rep
            user_rep = torch.max(user_rep, dim=2).values
        
        if self.construction == 'cat':

            # pdb.set_trace()
            if self.v_rep is not None:
                user_rep = self.v_rep[:self.num_user]
            if self.t_rep is not None:
                user_rep = self.t_rep[:self.num_user]
            if self.v_rep is not None and self.t_rep is not None:
                self.v_rep = torch.unsqueeze(self.v_rep, 2)
                self.t_rep = torch.unsqueeze(self.t_rep, 2)
                self.id_rep = torch.unsqueeze(self.id_rep, 2)
                user_rep = torch.cat((self.id_rep[:self.num_user], self.v_rep[:self.num_user], self.t_rep[:self.num_user]), dim=2)
                user_rep = self.weight_u.transpose(1, 2) * user_rep

                user_rep = torch.cat((user_rep[:, :, 0], user_rep[:, :, 1], user_rep[:, :, 2]), dim=1)
        item_rep = representation[self.num_user:]
        if self.has_item_graph:
            item_rep_new = item_rep
            for i in range(self.n_layers):
                item_rep_new = torch.sparse.mm(self.mm_adj, item_rep_new)
        user_rep_new = torch.cat((self.id_preference, self.v_preference, self.t_preference), dim=1)
        if self.has_user_graph:
            for i in range(self.n_layers):
                user_rep_new = torch.sparse.mm(self.user_adj, user_rep_new)
        # using graph spectral transformation methods, please carefully construct the spectral info
        # otherwise the performance will be very bad
        # we have pre-calculated the Laplacian and lap_user
        f_all, f_all_prop = self.Spec_Processor(user_rep, item_rep, item_rep_new, user_rep_new)
        user_out_rep, item_out_rep, user_aggr, item_aggr, user_out_mask, item_out_mask, hsreg, u_spec_comps, item_spec_comps, user_aggr_mask, item_aggr_mask = self.Spec_Operator(f_all, f_all_prop, user_rep, item_rep)
        return user_out_rep, item_out_rep, user_aggr, item_aggr, user_out_mask, item_out_mask, hsreg, u_spec_comps, item_spec_comps, user_aggr_mask, item_aggr_mask

    def topk_sample(self, k):
        user_graph_index = []
        count_num = 0
        user_weight_matrix = torch.zeros(len(self.user_graph_dict), k)
        tasike = []
        for i in range(k):
            tasike.append(0)
        for i in range(len(self.user_graph_dict)):
            if len(self.user_graph_dict[i][0]) < k:
                count_num += 1
                if len(self.user_graph_dict[i][0]) == 0:
                    # pdb.set_trace()
                    user_graph_index.append(tasike)
                    continue
                user_graph_sample = self.user_graph_dict[i][0][:k]
                user_graph_weight = self.user_graph_dict[i][1][:k]
                while len(user_graph_sample) < k:
                    rand_index = np.random.randint(0, len(user_graph_sample))
                    user_graph_sample.append(user_graph_sample[rand_index])
                    user_graph_weight.append(user_graph_weight[rand_index])
                user_graph_index.append(user_graph_sample)

                if self.user_aggr_mode == 'softmax':
                    user_weight_matrix[i] = F.softmax(torch.tensor(user_graph_weight), dim=0)  # softmax
                if self.user_aggr_mode == 'mean':
                    user_weight_matrix[i] = torch.ones(k) / k  # mean
                continue
            user_graph_sample = self.user_graph_dict[i][0][:k]
            user_graph_weight = self.user_graph_dict[i][1][:k]

            if self.user_aggr_mode == 'softmax':
                user_weight_matrix[i] = F.softmax(torch.tensor(user_graph_weight), dim=0)  # softmax
            if self.user_aggr_mode == 'mean':
                user_weight_matrix[i] = torch.ones(k) / k  # mean
            user_graph_index.append(user_graph_sample)

        # pdb.set_trace()
        return user_graph_index, user_weight_matrix

    def hinge_margin_loss(self, users, pos_items, neg_items, margin=1.0):
        """
        Pairwise hinge loss with margin: E[ max(0, margin - (s_pos - s_neg)) ]
        """
        pos_scores = torch.sum(users * pos_items, dim=1)
        neg_scores = torch.sum(users * neg_items, dim=1)
        return torch.mean(F.relu(margin - (pos_scores - neg_scores)))

    def sampled_softmax_ce_loss(self, users, pos_items, neg_items):
        """
        Listwise (sampled) softmax cross-entropy over {pos + K neg}.
        This is the classic "softmax loss" / "InfoNCE-style" loss.
        """
        # scores: (B, 1+K)
        pos_logits = torch.sum(users * pos_items, dim=1, keepdim=True)         # (B,1)
        neg_logits = torch.sum(users.unsqueeze(1) * neg_items, dim=-1)         # (B,K)
        logits = torch.cat([pos_logits, neg_logits], dim=1)                    # (B,1+K)

        # label=0 means the first column is the positive
        labels = torch.zeros(users.size(0), dtype=torch.long, device=users.device)
        return F.cross_entropy(logits, labels)

    def multi_mode_ce_loss(self,spectral_user_emb,spectral_item_pos_emb,spectral_item_neg_emb,spect_aggr_user_emb,spect_aggr_item_pos_emb,spect_aggr_item_neg_emb):
        """
        BCE-with-logits over (u, pos) vs (u, neg), with optional tower selection / mixing.
        """

        # == Aggregated Spectral logits
        aggr_pos_logit = torch.sum(spect_aggr_user_emb * spect_aggr_item_pos_emb, dim=1)
        aggr_neg_logit = torch.sum(spect_aggr_user_emb * spect_aggr_item_neg_emb, dim=1)

        # == Spectral logits
        spec_pos_logit = torch.sum(spectral_user_emb * spectral_item_pos_emb, dim=1)
        spec_neg_logit = torch.sum(spectral_user_emb * spectral_item_neg_emb, dim=1)

        # Gate value in (0,1), later we can use dynamic fusion
        fusion_gate = torch.sigmoid(self.fusion_gate)

        # --Pick logits according to mode
        if self.out_mode == "aggr":
            pos_logit, neg_logit = aggr_pos_logit, aggr_neg_logit
        elif self.out_mode == "spec":
            pos_logit, neg_logit = spec_pos_logit, spec_neg_logit
        elif self.out_mode == "mix":
            alpha = self.mix_alpha  # expected in [0,1]
            pos_logit = (1.0 - alpha) * aggr_pos_logit + alpha * spec_pos_logit
            neg_logit = (1.0 - alpha) * aggr_neg_logit + alpha * spec_neg_logit
        else:
            raise ValueError(f"Unknown out_mode={self.out_mode}")

        # --standard BCE-with-logits
        logits = torch.cat([pos_logit, neg_logit], dim=0)
        labels = torch.cat([torch.ones_like(pos_logit), torch.zeros_like(neg_logit)], dim=0)

        loss = F.binary_cross_entropy_with_logits(logits, labels)
        return loss

    def calculate_loss(self, interaction):
        users = interaction[0]
        pos_items = interaction[1]
        neg_items = interaction[2]
        #--
        user_out_emb, item_out_emb, user_aggr, item_aggr, user_out_mask, item_out_mask, hsreg, u_spec_comps, item_spec_comps, user_aggr_mask, item_aggr_mask = self.forward()

        u_out_batchs = user_out_emb[users]
        i_out_pos_batchs = item_out_emb[pos_items]
        i_out_neg_batchs = item_out_emb[neg_items]

        #--
        u_aggr_batchs = user_aggr[users]
        i_aggr_pos_batchs = item_aggr[pos_items]
        i_aggr_neg_batchs = item_aggr[neg_items]

        batch_ce_loss = self.multi_mode_ce_loss(u_out_batchs, i_out_pos_batchs, i_out_neg_batchs, u_aggr_batchs, i_aggr_pos_batchs, i_aggr_neg_batchs)

        #--
        user_spect = []
        item_spect = []
        for x in u_spec_comps:
            user_spect.append(x[users])
        for x in item_spec_comps:
            item_spect.append(x[pos_items])
        cl_loss = self.cl_contrast_loss(item_spect,user_spect,self.tau)

        consistent_loss= self.masked_consistency_mse(users, pos_items, neg_items,user_out_emb, item_out_emb,user_out_mask, item_out_mask,user_aggr, item_aggr,user_aggr_mask, item_aggr_mask)

        return batch_ce_loss + hsreg * self.reg_weight + consistent_loss * self.ma_weight + cl_loss * self.cl_weight

    def full_sort_predict(self, interaction):
        user_ids = interaction[0]

        # get spectral-enhanced and aggregated embeddings
        spec_user_emb, spec_item_emb, aggr_user_emb, aggr_item_emb, *_ = self.forward()

        # spectral-level scores
        query_spec_user = spec_user_emb[user_ids]                              # (B, D)
        spec_scores_all = torch.matmul(query_spec_user, spec_item_emb.t())     # (B, num_items)

        # aggregate-level scores
        query_aggr_user = aggr_user_emb[user_ids]                              # (B, D)
        aggr_scores_all = torch.matmul(query_aggr_user, aggr_item_emb.t())     # (B, num_items)

        # Gate value in (0,1). handy for dynamic fusion later.
        fusion_gate = torch.sigmoid(self.fusion_gate)

        if self.out_mode == "aggr":
            final_scores = aggr_scores_all
        elif self.out_mode == "spec":
            final_scores = spec_scores_all
        elif self.out_mode == "mix":
            alpha = self.mix_alpha
            final_scores = (1.0 - alpha) * aggr_scores_all + alpha * spec_scores_all
        else:
            raise ValueError(f"Unknown out_mode={self.out_mode}")

        # Full-sort scores against all items
        return final_scores

    def cl_contrast_loss(self,item_spec_comps,user_spec_comps=None,tau: float = 0.2,use_user: bool = True,user_weight: float = 1.0):
        """
        Cross-modal contrastive loss computed separately for item and maybe user.
        loss = item_loss + user_weight * user_loss
        """

        def _as_band_list(spec):
            if isinstance(spec, (list, tuple)):
                return list(spec)
            if torch.is_tensor(spec):
                assert spec.dim() == 3, f"Expect (B,M,3D), got {tuple(spec.shape)}"
                return [spec[:, m, :] for m in range(spec.size(1))]
            raise TypeError(f"Unsupported type: {type(spec)}")

        def _single_side_loss(spec_comps):
            # spec_comps: List[M] of (B, 3D)
            M = len(spec_comps)
            B, threeD = spec_comps[0].shape
            assert threeD % 3 == 0, f"Last dim must be divisible by 3, got {threeD}"
            D = threeD // 3
            device = spec_comps[0].device

            txt = torch.stack([torch.chunk(x, 3, dim=-1)[1] for x in spec_comps], dim=1)  # (B,M,D)
            vis = torch.stack([torch.chunk(x, 3, dim=-1)[2] for x in spec_comps], dim=1)  # (B,M,D)

            N = B * M
            txt = F.normalize(txt.reshape(N, D), dim=-1)  # (N,D)
            vis = F.normalize(vis.reshape(N, D), dim=-1)  # (N,D)

            bank = torch.cat([txt, vis], dim=0)           # (2N, D)

            logits_v = (vis @ bank.t()) / tau             # (N, 2N)
            target_v = torch.arange(N, device=device)    

            logits_t = (txt @ bank.t()) / tau
            target_t = torch.arange(N, device=device) + N 

            return 0.5 * (F.cross_entropy(logits_v, target_v) + F.cross_entropy(logits_t, target_t))

        item_spec_comps = _as_band_list(item_spec_comps)
        item_loss = _single_side_loss(item_spec_comps)

        if use_user:
            if user_spec_comps is None:
                raise ValueError("use_user=True but user_spec_comps is None.")
            user_spec_comps = _as_band_list(user_spec_comps)
            user_loss = _single_side_loss(user_spec_comps)
            return item_loss + user_weight * user_loss

        return item_loss

    def masked_consistency_mse(self, users, pos_items, neg_items,user_out_emb, item_out_emb,user_out_mask, item_out_mask, user_aggr=None, item_aggr=None,user_aggr_mask=None, item_aggr_mask=None):
        """
        Mask consistency loss (MSE) with a simple mode switch.
        """
        mode = self.out_mode
        alpha = self.mix_alpha
        # spec-level mse
        u_full = user_out_emb[users]
        pos_full = item_out_emb[pos_items]
        neg_full = item_out_emb[neg_items]

        u_mask = user_out_mask[users]
        pos_mask = item_out_mask[pos_items]
        neg_mask = item_out_mask[neg_items]

        mse_spec = (
            F.mse_loss(u_mask,  u_full.detach()) +
            F.mse_loss(pos_mask, pos_full.detach()) +
            F.mse_loss(neg_mask, neg_full.detach())
        ) / 3.0

        # aggr-level
        mse_aggr = None
        if (user_aggr is not None) and (item_aggr is not None) and (user_aggr_mask is not None) and (item_aggr_mask is not None):
            u_full_a = user_aggr[users]
            pos_full_a = item_aggr[pos_items]
            neg_full_a = item_aggr[neg_items]

            u_mask_a = user_aggr_mask[users]
            pos_mask_a = item_aggr_mask[pos_items]
            neg_mask_a = item_aggr_mask[neg_items]

            mse_aggr = (
                F.mse_loss(u_mask_a,  u_full_a.detach()) +
                F.mse_loss(pos_mask_a, pos_full_a.detach()) +
                F.mse_loss(neg_mask_a, neg_full_a.detach())
            ) / 3.0

        # mode switch
        if mode == "spec":
            return mse_spec

        if mode == "aggr":
            if mse_aggr is None:
                raise ValueError("mode='aggr' requires user_aggr item_aggr and their masked versions.")
            return mse_aggr

        if mode == "mix":
            if mse_aggr is None:
                raise ValueError("mode='mix' requires user_aggr item_aggr and their masked versions.")
            return (1.0 - alpha) * mse_aggr + alpha * mse_spec

        raise ValueError(f"Unknown mode={mode}")


class Diffusion3BandBank(nn.Module):
    """
    Stable 3-band decomposition by multi-scale diffusion:
      x_s = S^{t_small}(x)
      x_l = S^{t_large}(x)
      low  = x_l
      mid  = x_s - x_l
      high = x - x_s

    S = I - alpha * L_sym   (alpha in (0,1]) is safe for normalized Laplacian.
    """
    def __init__(self, t_small=2, t_large=8, alpha=0.5, use_ln=True, init_gain=0.0):
        super().__init__()
        assert t_small >= 1 and t_large > t_small
        self.t_small = t_small
        self.t_large = t_large
        self.alpha = alpha
        self.use_ln = use_ln

        # optional: residual injection gains, start from 0 => safe start
        self.gain = nn.Parameter(torch.tensor([init_gain, init_gain, init_gain], dtype=torch.float32))

    def _diffuse(self, x, L_sym):  # L_sym: sparse (N,N)
        # one diffusion step: x <- (I - alpha*L) x
        return x - self.alpha * torch.sparse.mm(L_sym, x)

    def forward(self, x: torch.Tensor, L_sym: torch.sparse.FloatTensor):
        L_sym = L_sym.coalesce()

        xs = x
        for _ in range(self.t_small):
            xs = self._diffuse(xs, L_sym)

        xl = xs
        for _ in range(self.t_large - self.t_small):
            xl = self._diffuse(xl, L_sym)

        low  = xl
        mid  = xs - xl
        high = x - xs

        if self.use_ln:
            low  = F.layer_norm(low,  (low.size(-1),))
            mid  = F.layer_norm(mid,  (mid.size(-1),))
            high = F.layer_norm(high, (high.size(-1),))

        # residual injection (recommended)
        g = torch.tanh(self.gain)
        out_low  = x + g[0] * low
        out_mid  = x + g[1] * mid
        out_high = x + g[2] * high

        return [out_low, out_mid, out_high]


def sparse_eye(n: int, device):
    idx = torch.arange(n, device=device)
    return torch.sparse_coo_tensor(
        torch.stack([idx, idx], dim=0),
        torch.ones(n, device=device),
        (n, n)
    ).coalesce()

def compute_low_high_basis_eigsh(L_sp: sp.csr_matrix, k_low=16, k_high=16, tol=1e-3, maxiter=2000):
    evals_low,  evecs_low  = eigsh(L_sp, k=k_low,  which="SM", tol=tol, maxiter=maxiter)
    evals_high, evecs_high = eigsh(L_sp, k=k_high, which="LM", tol=tol, maxiter=maxiter)
    return (
        evals_low.astype(np.float32),  evecs_low.astype(np.float32),
        evals_high.astype(np.float32), evecs_high.astype(np.float32),
    )

def torch_sparse_to_scipy_csr(L: "torch.Tensor") -> sp.csr_matrix:
    L = L.coalesce()
    idx = L.indices().cpu().numpy()
    val = L.values().cpu().numpy()
    N = L.size(0)
    return sp.csr_matrix((val, (idx[0], idx[1])), shape=(N, N))

class ChebFilterBank(nn.Module):
    """
    Chebyshev polynomial filter bank for graph signals.
    """

    def __init__(self, M: int, K_poly: int = 5):
        super().__init__()
        self.M, self.K = M, K_poly

        # Initialize as low-pass / band-pass / high-pass.
        # k=0 corresponds to T0 (identity), k=1 roughly correlates with lambda, etc.
        theta = torch.zeros(M, K_poly + 1)
        theta[0, 0] = 1.0        # low-pass: mainly keep T0
        theta[1, 1] = 0.8        # mid-band: emphasize first order
        theta[2, K_poly] = 0.5   # high-pass: emphasize higher order
        self.theta = nn.Parameter(theta)

    def forward(self, x: torch.Tensor, L_norm: torch.Tensor):
        """
        Args:
            x: (N, F) node features / graph signal
            L_norm: normalized Laplacian as a sparse tensor

        Returns:
            parts: List[M], each is (N, F) filtered signal for one band
        """
        # Chebyshev recursion: T0(x)=x, T1(x)=Lx, Tk(x)=2L Tk-1(x) - Tk-2(x)
        Tx_0 = x
        Tx_1 = torch.sparse.mm(L_norm, x)
        polys = [Tx_0, Tx_1]

        for _ in range(2, self.K + 1):
            Tx_2 = 2.0 * torch.sparse.mm(L_norm, Tx_1) - Tx_0
            polys.append(Tx_2)
            Tx_0, Tx_1 = Tx_1, Tx_2

        # Combine K+1 polynomials into M filters
        parts = [
            sum(self.theta[m, k] * polys[k] for k in range(self.K + 1))
            for m in range(self.M)
        ]
        return parts

class LogGainFilter(nn.Module):
    def __init__(self, shape, eps=0.1):
        super().__init__()
        self.eps = eps
        self.log_gain = nn.Parameter(torch.randn(*shape))

    def forward(self):
        return torch.exp(self.eps * torch.tanh(self.log_gain))

class HyperSpectralOperator(nn.Module):
    def __init__(self, in_dim=192, freq_dim=3, num_modalities=3, cp_rank=4):
        super().__init__()
        self.M = freq_dim
        self.d = in_dim     # 192
        self.rank = cp_rank
        self.tau = 1.0
        flatten_dim = self.M * self.d

        self.static_router = True
        
        # feature fusion MLP (Feature Mixer)
        # to flat all input feat
        self.encoder = nn.Sequential(
            nn.Linear(self.d, self.d//3),
            nn.GELU(),
            nn.Linear(self.d//3, self.d//3),
            #nn.LayerNorm(self.d) # 
        )

        self.freq_gate = nn.Sequential(
            nn.Linear(self.d, self.d // 3), 
            nn.GELU(),
            nn.Linear(self.d // 3, 1),    
            nn.Sigmoid()                   
        )

        self.V_scaleor = nn.Sequential(
            nn.Linear(in_dim, in_dim // 4),
            # nn.LayerNorm(self.d),
            nn.ReLU(),
            nn.Linear(in_dim // 4, in_dim),
            nn.Sigmoid()
        )

        self.Wq = nn.Parameter(torch.randn(self.M, self.rank))
        self.Wk = nn.Parameter(torch.randn(self.M, self.rank))

        self.V_filter = LogGainFilter(shape=(self.rank, in_dim))
        self.rank_w = nn.Parameter(torch.zeros(self.rank))
        self.rank_router = nn.Linear(in_dim, self.rank, bias=True)
        
        # output projection layer
        self.output_proj = nn.Linear(self.d, self.d//3, bias=False)
        
        #
        # keep initial new_scores to 0.0, avoid collapse
        nn.init.normal_(self.output_proj.weight, mean=0.0, std=1e-4)
        # initializer
        nn.init.xavier_normal_(self.Wq)
        nn.init.xavier_normal_(self.Wk)

    def forward(self, spect_compos, info_emb):
        """
        HyperSpectralOperator forward process.
        """
        spect_compos = torch.stack(spect_compos, dim=1)
        batch_size, num_bands, embed_dim = spect_compos.shape

        # inter-band kernel from rank-r factors
        # scores_{m,n,r} = Wq[m,r] * Wk[n,r]
        rank_scale = (self.rank ** 0.5) * self.tau
        scores_mnr = self.Wq[:, None, :] * self.Wk[None, :, :]          # (M, M, r)
        kernel_raw = scores_mnr.sum(dim=-1) / rank_scale                # (M, M)
        mixing_weights = F.softmax(kernel_raw, dim=0)                   # (M, M)
        # normalize contributions to each output band  
        # mix different bands with weights
        # (M,M) @ (B,M,D) -> (B,M,D)
        fused_bands = torch.einsum('mn, bnd -> bmd', mixing_weights, spect_compos) # (B, M, D)

        # rank-wise diagonal filtering and aggregation
        if self.static_router:
            rank_weights = torch.softmax(self.rank_w, dim=-1)               # (r,)
        else:
            rank_logits = self.rank_router(info_emb)                   # (B, R)
            rank_weights = F.softmax(rank_logits, dim=-1)              # (B, R)
            rank_weights = rank_weights.transpose(0, 1).unsqueeze(-1).unsqueeze(-1) # (R,B,1,1)

        Vdiag_filters = self.V_filter()   # Approximate in diagonal form to control the complexity (r, D)
        V_scale = self.V_scaleor(info_emb).unsqueeze(1)
        filtered_rank = fused_bands.unsqueeze(0) * Vdiag_filters[:, None, None, :]  # (r, B, M, D)
        
        # Aggregate over ranks using rank_weights with info-aware scale
        if self.static_router:
            fused_bands = V_scale * (filtered_rank * rank_weights[:, None, None, None]).sum(dim=0)  # (B, M, D)
        else:
            fused_bands = V_scale * (filtered_rank * rank_weights).sum(dim=0)  # (B, M, D)
        
        #
        fused_spectral_emb = fused_bands # use latter

        # add regs, effectively avoid collapse during the early stage of training
        kernel_reg = (kernel_raw ** 2).mean()
        v_reg = (self.V_filter.log_gain ** 2).mean()
        reg_all = kernel_reg + v_reg
        return fused_spectral_emb, reg_all


def scale_laplacian(L: torch.sparse.FloatTensor, n_iter: int = 20) -> torch.sparse.FloatTensor:
    """
    Scale a (sparse) Laplacian so its spectrum is mapped to approximately [-1, 1],
    i.e., L_scaled = (2 / lambda_max) * L - I.

    We estimate lambda_max with power iteration (sparse-safe).
    """
    n = L.size(0)
    x = torch.randn(n, 1, device=L.device)

    for _ in range(n_iter):
        x = torch.sparse.mm(L, x)
        x = x / (x.norm() + 1e-12)

    Lx = torch.sparse.mm(L, x)
    lambda_max = torch.dot(x.squeeze(-1), Lx.squeeze(-1))

    I = torch.eye(n, device=L.device).to_sparse()
    L_scaled = L * (2.0 / (lambda_max + 1e-12)) - I
    return L_scaled

def compute_topk_basis_from_laplacian(L_torch_sparse, k=64, which="SM"):
    # Convert torch sparse -> SciPy CSR (use float64 for numerical stability)
    L_csr = torch_sparse_to_scipy_csr(L_torch_sparse).astype(np.float64)

    # Compute k smallest eigenpairs
    evals, evecs = eigsh(L_csr, k=k, which=which, tol=1e-3, maxiter=2000)

    # Cast to float32 for storage
    return evals.astype(np.float32), evecs.astype(np.float32)


class ContextAwareGateSigmoid(nn.Module):
    """
    Context-aware band gate (sigmoid).
    """
    def __init__(self, task_dim: int, M: int, hidden: int = 128, init_bias: float = 0.0):
        super().__init__()
        self.task_dim = task_dim
        self.M = M

        self.fc1 = nn.Linear(task_dim, hidden)
        self.fc2 = nn.Linear(hidden, M)

        # Make the initial gate close to sigmoid(init_bias)
        # Zeroing fc2.weight makes the initial logits depend only on bias (more stable/reproducible).
        nn.init.zeros_(self.fc2.weight)
        nn.init.constant_(self.fc2.bias, init_bias)

    def forward(self, context_emb: torch.Tensor) -> torch.Tensor:
        assert context_emb.dim() == 2 and context_emb.size(-1) == self.task_dim, \
            f"Expected (N, {self.task_dim}), got {tuple(context_emb.shape)}"

        h = F.relu(self.fc1(context_emb))      # (N, hidden)
        logits = self.fc2(h)                # (N, M)
        gate = torch.sigmoid(logits).unsqueeze(-1)  # (N, M, 1)
        return gate


class GraphSpectWeightModule(nn.Module):
    def __init__(self, in_dim=192, freq_dim=3, init_bias=0.0):
        super().__init__()
        self.in_dim = in_dim
        self.M = freq_dim

        # use self.context_leaner to merge info from emb and freq
        self.context_leaner = nn.Sequential(
            nn.Linear(in_dim * 2, in_dim // 4),
            nn.ReLU(),
            nn.Linear(in_dim // 4, freq_dim)  # logits for each band
        )
        self.fusion_gate = nn.Parameter(torch.tensor(0.1))
        # keep our initinal seeting
        nn.init.normal_(self.context_leaner[-1].weight, mean=0.0, std=1e-3)
        nn.init.zeros_(self.context_leaner[-1].bias)

    def forward(self, spect_mixed: torch.Tensor, info_emb: torch.Tensor) -> torch.Tensor:
        # spect_compos: (B,M,D), info_emb: (B,D)
        assert spect_mixed.dim() == 3, f"Expect spect_mixed (B,M,D), got {spect_mixed.shape}"
        assert info_emb.dim() == 2, f"Expect info_emb (B,D), got {info_emb.shape}"
        B, M, D = spect_mixed.shape
        assert M == self.M, f"Expect M={self.M}, got {M}"
        assert D == self.in_dim, f"Expect D={self.in_dim}, got {D}"
        assert info_emb.shape == (B, D), f"Expect info_emb {(B, D)}, got {info_emb.shape}"

        spectral_context = spect_mixed.mean(dim=1)                 # (B,D)
        combined = torch.cat([info_emb, spectral_context], dim=-1)  # (B,2D)
        logits = self.context_leaner(combined)                    # (B,M)
        weights = 1 + self.fusion_gate * torch.tanh(logits)                # (B,M) in (0,1)
        #weights = weights / (weights.mean(dim=1, keepdim=True) + 1e-6) 

        # weighted fusion
        x_mixed_weighted = spect_mixed * weights.unsqueeze(-1)

        # keep total scale consistent
        pre = spect_mixed.sum(dim=1)           # (B,D)
        post = x_mixed_weighted.sum(dim=1) 
        scale = (pre.norm(dim=-1, keepdim=True) + 1e-6) / (post.norm(dim=-1, keepdim=True) + 1e-6)
        x_mixed_weighted = x_mixed_weighted * scale.unsqueeze(1)

        user_agg = x_mixed_weighted.sum(dim=1)      # used for all fusion score
        user_each = x_mixed_weighted.reshape(B, -1) # used for band-level fusion score
        return user_each, user_agg


class User_Graph_sample(torch.nn.Module):
    def __init__(self, num_user, aggr_mode, dim_latent):
        super(User_Graph_sample, self).__init__()
        self.num_user = num_user
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode

    def forward(self, features, user_graph, user_matrix):
        index = user_graph
        u_features = features[index]
        user_matrix = user_matrix.unsqueeze(1)
        # pdb.set_trace()
        u_pre = torch.matmul(user_matrix, u_features)
        u_pre = u_pre.squeeze()
        return u_pre


class GCN(torch.nn.Module):
    def __init__(self, datasets, batch_size, num_user, num_item, dim_id, aggr_mode, num_layer, has_id, dropout,
                 dim_latent=None, device=None, features=None):
        super(GCN, self).__init__()
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.datasets = datasets
        self.dim_id = dim_id
        self.dim_feat = features.size(1)
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode
        self.num_layer = num_layer
        self.has_id = has_id
        self.dropout = dropout
        self.device = device

        if self.dim_latent:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
                gain=1).to(self.device))
            self.MLP = nn.Linear(self.dim_feat, 4 * self.dim_latent)
            self.MLP_1 = nn.Linear(4 * self.dim_latent, self.dim_latent)
            self.conv_embed_layer = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)
        else:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_feat), dtype=torch.float32, requires_grad=True),
                gain=1).to(self.device))
            self.conv_embed_layer = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

    def forward(self, edge_index_drop, edge_index, features):
        temp_features = self.MLP_1(F.leaky_relu(self.MLP(features))) if self.dim_latent else features
        x = torch.cat((self.preference, temp_features), dim=0).to(self.device)
        x = F.normalize(x).to(self.device)
        outs = [x]
        h = x
        for _ in range(self.num_layer):
            h = self.conv_embed_layer(h, edge_index)
            outs.append(h)
        x_hat = sum(outs)
        return x_hat, self.preference

class Base_gcn(MessagePassing):
    def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
        super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
        self.aggr = aggr
        self.in_channels = in_channels
        self.out_channels = out_channels

    def forward(self, x, edge_index, size=None):
        # pdb.set_trace()
        if size is None:
            edge_index, _ = remove_self_loops(edge_index)
            # edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
        x = x.unsqueeze(-1) if x.dim() == 1 else x
        # pdb.set_trace()
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x)

    def message(self, x_j, edge_index, size):
        if self.aggr == 'add':
            # pdb.set_trace()
            row, col = edge_index
            deg = degree(row, size[0], dtype=x_j.dtype)
            deg_inv_sqrt = deg.pow(-0.5)
            norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
            return norm.view(-1, 1) * x_j
        return x_j

    def update(self, aggr_out):
        return aggr_out

    def __repr(self):
        return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)


class SpectralCalculateOperator(nn.Module):
    def __init__(self, id_dim, v_dim, t_dim, M, device, mask_flag="band_drop", mask_rate=0.1, hidden_dim=128):
        super(SpectralCalculateOperator, self).__init__()
        self.M = M
        self.id_dim = id_dim
        self.v_dim = v_dim
        self.t_dim = t_dim
        self.device = device
        self.concat_dim = id_dim + v_dim + t_dim
        # here define operator
        self.spectral_op1 = HyperSpectralOperator(
            in_dim=self.concat_dim,
            freq_dim=M
        )
        self.spectral_op2 = HyperSpectralOperator(
            in_dim=self.concat_dim,
            freq_dim=M
        )
        # here define spectral gated module
        self.adapt_spect1 = GraphSpectWeightModule(in_dim=self.concat_dim, freq_dim=M)
        self.adapt_spect2 = GraphSpectWeightModule(in_dim=self.concat_dim, freq_dim=M)
        # mode
        self.mask_flag = mask_flag # "band_drop" or "noise_inter" or "none"
        self.mask_rate = mask_rate
        self.band_drop = BandLevelMask(M=M, mask_rate=mask_rate, rescale=True, ensure_one_band=True)
        self.noise_inter = BandNoiseIntervention(M=M, mask_rate=mask_rate, ensure_one_band=True, noise_scale=1.0)

    def forward(self, f_all, f_all_prop, user_rep, item_rep):
        """
        output: 
            user_out and item_out: means spectral-level concated representations
            user_aggr and item_aggr: means spectral-level aggregated representations
            in experiments, we found that different output rep will have different affect
        """
        spec_component_u      = [x[:user_rep.size(0)] for x in f_all]
        spec_component_i      = [x[user_rep.size(0):] for x in f_all]
        spec_component_u_new = [x[:user_rep.size(0)] for x in f_all_prop]
        spec_component_i_new = [x[user_rep.size(0):] for x in f_all_prop]
        spec_component_u = [spec_component_u[i] + spec_component_u_new[i] for i in range(self.M)]
        spec_component_i = [spec_component_i[i] + spec_component_i_new[i] for i in range(self.M)]
        
        #---
        u_fused_rep, hs_u = self.spectral_op1(spec_component_u,user_rep)
        # get fused-spectral rep and aggregated rep
        user_out, user_aggr = self.adapt_spect1(u_fused_rep, user_rep)
        # 
        i_fused_rep, hs_i = self.spectral_op2(spec_component_i,item_rep)   
        # the same for the item rep
        item_out, item_aggr = self.adapt_spect2(i_fused_rep, item_rep)
        # reg term to help train
        hsno_reg = hs_u + hs_i
        #---
        # doing mask from spectral perspective
        spec_u_componet_masked = self.apply_spect_mask(spec_component_u)
        u_fused_rep_mask, hs_u_mask = self.spectral_op1(spec_u_componet_masked,user_rep)
        user_out_mask, user_aggr_mask = self.adapt_spect1(u_fused_rep_mask, user_rep)
        # the same for items
        spec_i_componet_masked = self.apply_spect_mask(spec_component_i)
        i_fused_rep_mask, hs_i_mask = self.spectral_op2(spec_i_componet_masked,item_rep)
        item_out_mask, item_aggr_mask = self.adapt_spect2(i_fused_rep_mask, item_rep)
        hsno_reg_mask = hs_u_mask + hs_i_mask
        hsno_reg = hsno_reg + hsno_reg_mask
        #---
        return user_out, item_out, user_aggr, item_aggr, user_out_mask, item_out_mask, hsno_reg, spec_component_u, spec_component_i, user_aggr_mask, item_aggr_mask

    def apply_spect_mask(self, spec_component):
        """
        Apply spectral masking.
        - If input is List[M] of (B, D), stack to (B, M, D), apply mask
        """
        is_list_input = isinstance(spec_component, (list, tuple))
        if is_list_input:
            # List[M] of (B, D) -> (B, M, D)
            spec_tensor = torch.stack(spec_component, dim=1)
        else:
            spec_tensor = spec_component

        # Apply mask on tensor form
        if self.mask_flag == "band_drop":
            masked = self.band_drop(spec_tensor)
        elif self.mask_flag == "noise_inter":
            masked = self.noise_inter(spec_tensor)
        else:
            masked = spec_tensor

        # Restore to original type
        if is_list_input:
            # (B, M, D) -> List[M] of (B, D)
            return [masked[:, m, :] for m in range(masked.size(1))]
        return masked

class BandLevelMask(nn.Module):
    """
    Band-wise dropout mask, each sample has its own mask over M bands.
    divide by keep_prob to keep expected magnitude stable.
    """
    def __init__(self, M: int, mask_rate: float = 0.2, rescale: bool = True, ensure_one_band: bool = True):
        super().__init__()
        assert 0.0 <= mask_rate < 1.0
        self.M = M
        self.mask_rate = mask_rate
        self.rescale = rescale
        self.ensure_one_band = ensure_one_band

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        assert x.dim() == 3, f"expect (B,M,D), got {x.shape}"
        B, M, D = x.shape
        assert M == self.M, f"M mismatch: x has {M}, but self.M={self.M}"

        # (B, M, 1) mask
        mask = (torch.rand(B, M, 1, device=x.device) > self.mask_rate).float()

        # avoid all-zero mask per sample
        if self.ensure_one_band:
            all_zero = (mask.sum(dim=1) == 0)  # (B,1)
            if all_zero.any():
                idx = torch.where(all_zero.squeeze(-1))[0]
                # simplest: always keep band 0
                mask[idx, 0, 0] = 1.0

        out = x * mask

        if self.rescale:
            keep = 1.0 - self.mask_rate
            out = out / (keep + 1e-12)

        return out

class BandNoiseIntervention(nn.Module):
    """
    Band-wise intervention, replaced bands become Gaussian noise
    avoid all bands replaced for a sample
    """
    def __init__(self, M: int, mask_rate: float = 0.2, ensure_one_band: bool = True, noise_scale: float = 1.0):
        super().__init__()
        assert 0.0 <= mask_rate < 1.0
        self.M = M
        self.mask_rate = mask_rate
        self.ensure_one_band = ensure_one_band
        self.noise_scale = noise_scale

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        assert x.dim() == 3, f"expect (B,M,D), got {x.shape}"
        B, M, D = x.shape
        assert M == self.M, f"M mismatch: x has {M}, but self.M={self.M}"

        # (B, M, 1) keep-mask: 1 keep, 0 replace
        gamma = (torch.rand(B, M, 1, device=x.device) > self.mask_rate).float()

        if self.ensure_one_band:
            all_zero = (gamma.sum(dim=1) == 0)  # (B,1)
            if all_zero.any():
                idx = torch.where(all_zero.squeeze(-1))[0]
                gamma[idx, 0, 0] = 1.0

        noise = torch.randn_like(x) * self.noise_scale
        out = x * gamma + noise * (1.0 - gamma)
        return out


class SpectralGraphSignalProcessor(nn.Module):
    def __init__(self, id_dim, v_dim, t_dim, M, K_poly, device, hidden_dim=128, use_wavelet: bool = True):
        super(SpectralGraphSignalProcessor, self).__init__()
        self.M = M
        self.id_dim = id_dim
        self.v_dim = v_dim
        self.t_dim = t_dim
        self.device = device
        self.use_wavelet = use_wavelet
        # Injection from main process before training
        self.register_buffer("lap_user", None)   # (N_u+N_i, N_u+N_i)
        self.register_buffer("lap_item", None)   # now share with lap_user
        self.register_buffer("wavelet_basis", None)  # could be used for wavelet
        # define bank
        self.cheb_bank = ChebFilterBank(M=M, K_poly=K_poly)
        self.diff_bank = Diffusion3BandBank(
            t_small=2, t_large=8, alpha=0.5,
            use_ln=True, init_gain=0.0
        )

        # ===== Wavelet / GFT cache =====
        self.basis_cache_path = f"./cache/spectral_basis.pt"

        # borders, it's more stable to use fixed splitting, avoid energy changing
        self.fixed_borders = True   #bool(config.get("fixed_borders", True))

        # register these before training
        self.wavelet_basis = None   # (N, K)
        self.evals = None
        self.K = None
        self.borders = None

        self.full_basis_cache_path = f"./cache/full_eigh_basis_NA.pt"  # running with num_nodes
        self.full_basis_dtype = torch.float16  # saving use fp16 to save half space
        self._basis_ready = False

        self.full_max_nodes = 5000      # N <= 5000 using full-eigh, else using cheb
        self.cheb_K = K_poly                # Polynomial order
        

    def forward(self, user_rep, item_rep, new_item_rep, new_user_rep):
        """
        Here we use graph spectral transformations:
        Be attention: this part should be carefully designed, otherwise, the performance will drop apparently.
        """
        if self.use_wavelet and (self.lap_user is not None):
            all_rep  = torch.cat([user_rep, item_rep], dim=0)   # (N, F1)
            all_prop = torch.cat([new_user_rep, new_item_rep],  dim=0)    # (N, F2)

            F1 = all_rep.size(1)
            all_cat = torch.cat([all_rep, all_prop], dim=1)     # (N, F1+F2)

            f_all_cat = self._wavelet_band(all_cat, self.lap_user)   # List[M], each (N, F1+F2)

            f_all      = [x[:, :F1] for x in f_all_cat]
            f_all_prop = [x[:, F1:] for x in f_all_cat]
        else:
            raise Exception("No Spectral graph signal")

        return f_all, f_all_prop
    
    @staticmethod
    def _split_sizes(F: int, M: int):
        base, rem = divmod(F, M)
        return [base + (1 if i < rem else 0) for i in range(M)]

    def _wavelet_band(self, rep: torch.Tensor, lap: torch.Tensor):
        N = lap.size(0)

        # small graph: use full path (our best one
        if N > self.full_max_nodes:
            #print(">>>>> Big Graph")

            # big graph: use cheb with enforce reconstruct
            parts = self._cheb_mband_with_transformation(rep, lap)

            return parts
        else:
            #print(">>>>>")
            self.ensure_full_basis_cached(lap, cache_path=None, device=rep.device)
            B = self.wavelet_basis
            if B.dtype != torch.float32:
                B = B.float()

            coeff = B.T @ rep
            power = (coeff ** 2).sum(dim=1)
            cum = torch.cumsum(power, 0) / (power.sum() + 1e-12)
            K = B.size(1)
            
            # Split into self.M bands by cumulative energy
            thresholds = [i / self.M for i in range(1, self.M)]  # 1/M, 2/M, ..., (M-1)/M
            borders = [0] + [int((cum < t).sum()) for t in thresholds] + [K]

            parts = []
            for s, e in zip(borders[:-1], borders[1:]):
                parts.append(B[:, s:e] @ coeff[s:e])
            return parts
        
    

    def _cheb_apply(self, x: torch.Tensor, L_scaled: torch.sparse.FloatTensor, theta: torch.Tensor):
        """
        theta: (K+1,)  Chebyshev coefficients
        return: (N,F)
        """
        K = theta.numel() - 1
        Tx_0 = x
        out = theta[0] * Tx_0

        if K >= 1:
            Tx_1 = torch.sparse.mm(L_scaled, x)
            out = out + theta[1] * Tx_1
        else:
            return out

        for k in range(2, K + 1):
            Tx_2 = 2.0 * torch.sparse.mm(L_scaled, Tx_1) - Tx_0
            out = out + theta[k] * Tx_2
            Tx_0, Tx_1 = Tx_1, Tx_2

        return out

    def _cheb_mband_with_transformation(self, rep: torch.Tensor, lap: torch.sparse.FloatTensor, M: int = None):
        """
        General M-band Chebyshev decomposition
        """
        if M is None:
            M = self.M
        assert M >= 2, f"M must be >= 2, got {M}"

        # 1) scaled Laplacian (sparse)
        L_scaled = lap
        if not L_scaled.is_sparse:
            L_scaled = L_scaled.to_sparse()
        L_scaled = L_scaled.coalesce()

        device = rep.device
        dtype = rep.dtype
        K = self.cheb_K  # e.g., 5

        if M == 3:
            theta_low = torch.zeros(K + 1, device=device, dtype=dtype)
            theta_mid = torch.zeros(K + 1, device=device, dtype=dtype)

            theta_low[0] = 1.0
            theta_low[1] = -0.5

            if K >= 2:
                theta_mid[2] = 0.8
            if K >= 3:
                theta_mid[3] = 0.3

            low = self._cheb_apply(rep, L_scaled, theta_low)
            mid = self._cheb_apply(rep, L_scaled, theta_mid)
            high = rep - low - mid
            return [low, mid, high]
        
        # band0: "low" same style as before
        thetas = []

        theta0 = torch.zeros(K + 1, device=device, dtype=dtype)
        theta0[0] = 1.0
        if K >= 1:
            theta0[1] = -0.5
        thetas.append(theta0)

        # remaining bands (1 .. M-2): allocate Cheb orders 2..K across them
        # if K is small, some bands may become near-zero, residual will absorb the rest.
        num_mid = M - 2
        if num_mid > 0:
            orders = list(range(2, K + 1))  # candidate higher orders
            if len(orders) == 0:
                # no higher orders available -> all mid filters are zeros
                for _ in range(num_mid):
                    thetas.append(torch.zeros(K + 1, device=device, dtype=dtype))
            else:
                # split orders into num_mid contiguous groups
                # e.g., orders=[2,3,4,5], num_mid=2 -> [[2,3],[4,5]]
                groups = [orders[i::num_mid] for i in range(num_mid)]

                for g in groups:
                    theta = torch.zeros(K + 1, device=device, dtype=dtype)
                    # Use a simple decaying pattern like our mid band (0.8, 0.3, 0.1, ...)
                    # Keeps it stable and "band-like".
                    base = 0.8
                    decay = 0.375  # 0.8*0.375 ≈ 0.3
                    for j, k_ord in enumerate(g):
                        theta[k_ord] = base * (decay ** j)
                    thetas.append(theta)

        # Apply first (M-1) filters
        bands = []
        sum_prev = 0.0
        for theta in thetas:  # length == (M-1)
            b = self._cheb_apply(rep, L_scaled, theta)
            bands.append(b)
            sum_prev = sum_prev + b

        # Last band: residual
        bands.append(rep - sum_prev)
        return bands

    def _wavelet_band_pure(self, rep: torch.Tensor, lap: torch.Tensor):
        # make sure full basis exists
        self.ensure_full_basis_cached(lap, cache_path=None, device=rep.device)

        # identical to our best version
        B = self.wavelet_basis
        # fp16 basis is fine for storage, but matmul should be fp32 for stability
        if B.dtype != torch.float32:
            B = B.float()

        coeff = B.T @ rep                                # (K,F)
        power = (coeff**2).sum(dim=1)                    # (K,)

        cum = torch.cumsum(power, 0) / (power.sum() + 1e-12)
        K = B.size(1)
        borders = [0] + [int((cum < t).sum()) for t in (1/3, 2/3)] + [K]

        parts = []
        for s, e in zip(borders[:-1], borders[1:]):
            parts.append(B[:, s:e] @ coeff[s:e])          # (N,F)
        return parts

    def ensure_full_basis_cached(self, lap: torch.Tensor, cache_path: str = None, device=None):
        """
        Cache eigenvectors computed by torch.linalg.eigh on dense Laplacian.
        Saves fp16 evecs to reduce disk size, Converts to fp32 during multiplication for stability.
        """
        if getattr(self, "wavelet_basis", None) is not None and getattr(self, "evals", None) is not None:
            self._basis_ready = True
            return

        if device is None:
            device = lap.device
        is_dist = torch.distributed.is_available() and torch.distributed.is_initialized()
        rank = torch.distributed.get_rank() if is_dist else 0

        N = lap.size(0)
        if cache_path is None:
            cache_path = f"./cache/full_eigh_basis_N{N}.pt"

        # ---- load if exists ----
        if os.path.exists(cache_path):
            ckpt = torch.load(cache_path, map_location="cpu")
            if ckpt.get("num_nodes", None) == N:
                self.wavelet_basis = ckpt["evecs"].to(device)
                self.evals = ckpt["evals"].to(device)
                self.K = self.wavelet_basis.size(1)
                self._basis_ready = True
                return
            else:
                # mismatch -> remove old cache
                try:
                    os.remove(cache_path)
                except:
                    pass

        # ---- compute on rank0 ----
        if rank == 0:
            os.makedirs(os.path.dirname(cache_path) or ".", exist_ok=True)

            L = lap.to_dense()  # MUST fit in memory
            evals, evecs = torch.linalg.eigh(L)  # evals:(N,), evecs:(N,N)

            # store as fp16 to save disk; evals keep fp32
            evecs_cpu = evecs.to(dtype=self.full_basis_dtype).cpu()
            evals_cpu = evals.to(dtype=torch.float32).cpu()

            torch.save({"num_nodes": N, "evals": evals_cpu, "evecs": evecs_cpu}, cache_path)

        if is_dist:
            torch.distributed.barrier()

        ckpt = torch.load(cache_path, map_location="cpu")
        self.wavelet_basis = ckpt["evecs"].to(device)
        self.evals = ckpt["evals"].to(device)
        self.K = self.wavelet_basis.size(1)
        self._basis_ready = True

    def _diffusion_band(self, rep: torch.Tensor, lap_sym: torch.Tensor):
        return self.diff_bank(rep, lap_sym)

    def _wavelet_band_full(self, rep: torch.Tensor, lap: torch.Tensor):
        if self.wavelet_basis is None:
            L = lap.to_dense()
            # --Take more eigenvectors
            K = L.size(0)  # min(10000, L.size(0))  # 2000≈F*10; if memory allows, directly use N
            self.K = K
            evals, evecs = torch.linalg.eigh(L)          # (N,N)
            self.evals = evals[:K]                       # store eigenvalues
            self.wavelet_basis = evecs[:, :K]            # (N,K)
        else:
            K = self.K

        B = self.wavelet_basis                           # (N,K)
        coeff = B.T @ rep                                # (K,F)
        power = (coeff**2).sum(dim=1)                    # energy per lambda_i  (K,)

        # --Split into bands by cumulative energy
        cum = torch.cumsum(power, 0) / power.sum()       # cumulative energy ratio
        # boundaries at t = 1/M, 2/M, ..., (M-1)/M
        thresholds = [(i / self.M) for i in range(1, self.M)]
        borders = [0] + [int((cum < t).sum()) for t in thresholds] + [K]

        parts = []
        for s, e in zip(borders[:-1], borders[1:]):
            part = B[:, s:e] @ coeff[s:e]                # (N,F)
            # part = F.layer_norm(part, part.shape[-1:])
            parts.append(part)
        return parts   

    def _wavelet_with_fixeborder(self, rep: torch.Tensor, lap: torch.Tensor):
        # ensure we've already get the cached basis
        self.ensure_basis_cached(self.basis_cache_path, k=self.num_eig, device=rep.device)

        B = self.wavelet_basis      # (N, K)  on device
        K = self.K

        # spectral coeff
        coeff = B.T @ rep           # (K, F)

        # borders: follow fixed setting to ensure stable
        borders = [0, K // 3, 2 * K // 3, K]

        parts = []
        for s, e in zip(borders[:-1], borders[1:]):
            parts.append(B[:, s:e] @ coeff[s:e])  # (N, F)
        return parts

    def ensure_basis_cached(self, cache_path: str, k_low=16, k_high=16, device=None):
        if getattr(self, "basis_low", None) is not None:
            return

        if device is None:
            device = next(self.parameters()).device

        is_dist = torch.distributed.is_available() and torch.distributed.is_initialized()
        rank = torch.distributed.get_rank() if is_dist else 0

        if os.path.exists(cache_path):
            ckpt = torch.load(cache_path, map_location="cpu")
            self.basis_low  = ckpt["basis_low"].to(device)   # (N,k_low)
            self.basis_high = ckpt["basis_high"].to(device)  # (N,k_high)
            return

        if rank == 0:
            assert hasattr(self, "lap_user_raw") and (self.lap_user_raw is not None)

            L_sp = torch_sparse_to_scipy_csr(self.lap_user_raw).astype(np.float64)
            _, eL, _, eH = compute_low_high_basis_eigsh(L_sp, k_low=k_low, k_high=k_high)

            basis_low  = torch.from_numpy(eL).float()   # CPU
            basis_high = torch.from_numpy(eH).float()

            os.makedirs(os.path.dirname(cache_path) or ".", exist_ok=True)
            torch.save({
                "basis_low": basis_low,
                "basis_high": basis_high,
                "k_low": k_low,
                "k_high": k_high,
                "num_nodes": basis_low.size(0),
            }, cache_path)

        if is_dist:
            torch.distributed.barrier()

        ckpt = torch.load(cache_path, map_location="cpu")
        self.basis_low  = ckpt["basis_low"].to(device)
        self.basis_high = ckpt["basis_high"].to(device)
